/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooq;


import com.example.demo.jooq.tables.Answersintervalsgame;
import com.example.demo.jooq.tables.Answersnotesgame;
import com.example.demo.jooq.tables.Intervals;
import com.example.demo.jooq.tables.Intervalsgame;
import com.example.demo.jooq.tables.Levelintervals;
import com.example.demo.jooq.tables.Levelnotes;
import com.example.demo.jooq.tables.Notes;
import com.example.demo.jooq.tables.Notesgames;
import com.example.demo.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Db extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>db</code>
     */
    public static final Db DB = new Db();

    /**
     * The table <code>db.AnswersIntervalsGame</code>.
     */
    public final Answersintervalsgame ANSWERSINTERVALSGAME = Answersintervalsgame.ANSWERSINTERVALSGAME;

    /**
     * The table <code>db.AnswersNotesGame</code>.
     */
    public final Answersnotesgame ANSWERSNOTESGAME = Answersnotesgame.ANSWERSNOTESGAME;

    /**
     * The table <code>db.Intervals</code>.
     */
    public final Intervals INTERVALS = Intervals.INTERVALS;

    /**
     * The table <code>db.IntervalsGame</code>.
     */
    public final Intervalsgame INTERVALSGAME = Intervalsgame.INTERVALSGAME;

    /**
     * The table <code>db.LevelIntervals</code>.
     */
    public final Levelintervals LEVELINTERVALS = Levelintervals.LEVELINTERVALS;

    /**
     * The table <code>db.LevelNotes</code>.
     */
    public final Levelnotes LEVELNOTES = Levelnotes.LEVELNOTES;

    /**
     * The table <code>db.Notes</code>.
     */
    public final Notes NOTES = Notes.NOTES;

    /**
     * The table <code>db.NotesGames</code>.
     */
    public final Notesgames NOTESGAMES = Notesgames.NOTESGAMES;

    /**
     * The table <code>db.Users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Db() {
        super("db", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Answersintervalsgame.ANSWERSINTERVALSGAME,
            Answersnotesgame.ANSWERSNOTESGAME,
            Intervals.INTERVALS,
            Intervalsgame.INTERVALSGAME,
            Levelintervals.LEVELINTERVALS,
            Levelnotes.LEVELNOTES,
            Notes.NOTES,
            Notesgames.NOTESGAMES,
            Users.USERS
        );
    }
}
