/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooq;


import com.example.demo.jooq.tables.Answersintervalsgame;
import com.example.demo.jooq.tables.Answersnotesgame;
import com.example.demo.jooq.tables.Intervalsgame;
import com.example.demo.jooq.tables.Levelintervals;
import com.example.demo.jooq.tables.Levelnotes;
import com.example.demo.jooq.tables.Notesgames;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index LEVELNOTES_HIGHERNOTEBOUND = Internal.createIndex(DSL.name("higherNoteBound"), Levelnotes.LEVELNOTES, new OrderField[] { Levelnotes.LEVELNOTES.HIGHERNOTEBOUND }, false);
    public static final Index ANSWERSINTERVALSGAME_INTERVALID = Internal.createIndex(DSL.name("intervalID"), Answersintervalsgame.ANSWERSINTERVALSGAME, new OrderField[] { Answersintervalsgame.ANSWERSINTERVALSGAME.INTERVALID }, false);
    public static final Index INTERVALSGAME_INTERVALLEVELID = Internal.createIndex(DSL.name("intervalLevelID"), Intervalsgame.INTERVALSGAME, new OrderField[] { Intervalsgame.INTERVALSGAME.INTERVALLEVELID }, false);
    public static final Index ANSWERSINTERVALSGAME_INTERVALSGAMEID = Internal.createIndex(DSL.name("intervalsGameID"), Answersintervalsgame.ANSWERSINTERVALSGAME, new OrderField[] { Answersintervalsgame.ANSWERSINTERVALSGAME.INTERVALSGAMEID }, false);
    public static final Index NOTESGAMES_LEVELNOTESID = Internal.createIndex(DSL.name("levelNotesID"), Notesgames.NOTESGAMES, new OrderField[] { Notesgames.NOTESGAMES.LEVELNOTESID }, false);
    public static final Index LEVELNOTES_LOWERNOTEBOUND = Internal.createIndex(DSL.name("lowerNoteBound"), Levelnotes.LEVELNOTES, new OrderField[] { Levelnotes.LEVELNOTES.LOWERNOTEBOUND }, false);
    public static final Index ANSWERSNOTESGAME_NOTEID = Internal.createIndex(DSL.name("noteID"), Answersnotesgame.ANSWERSNOTESGAME, new OrderField[] { Answersnotesgame.ANSWERSNOTESGAME.NOTEID }, false);
    public static final Index ANSWERSNOTESGAME_NOTESGAMEID = Internal.createIndex(DSL.name("notesGameID"), Answersnotesgame.ANSWERSNOTESGAME, new OrderField[] { Answersnotesgame.ANSWERSNOTESGAME.NOTESGAMEID }, false);
    public static final Index INTERVALSGAME_USERID = Internal.createIndex(DSL.name("userID"), Intervalsgame.INTERVALSGAME, new OrderField[] { Intervalsgame.INTERVALSGAME.USERID }, false);
    public static final Index LEVELINTERVALS_USERID = Internal.createIndex(DSL.name("userID"), Levelintervals.LEVELINTERVALS, new OrderField[] { Levelintervals.LEVELINTERVALS.USERID }, false);
    public static final Index LEVELNOTES_USERID = Internal.createIndex(DSL.name("userID"), Levelnotes.LEVELNOTES, new OrderField[] { Levelnotes.LEVELNOTES.USERID }, false);
    public static final Index NOTESGAMES_USERID = Internal.createIndex(DSL.name("userID"), Notesgames.NOTESGAMES, new OrderField[] { Notesgames.NOTESGAMES.USERID }, false);
}
