/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooq;


import com.example.demo.jooq.tables.Answersintervalsgame;
import com.example.demo.jooq.tables.Answersnotesgame;
import com.example.demo.jooq.tables.Intervals;
import com.example.demo.jooq.tables.Intervalsgame;
import com.example.demo.jooq.tables.Levelintervals;
import com.example.demo.jooq.tables.Levelnotes;
import com.example.demo.jooq.tables.Notes;
import com.example.demo.jooq.tables.Notesgames;
import com.example.demo.jooq.tables.Users;
import com.example.demo.jooq.tables.records.AnswersintervalsgameRecord;
import com.example.demo.jooq.tables.records.AnswersnotesgameRecord;
import com.example.demo.jooq.tables.records.IntervalsRecord;
import com.example.demo.jooq.tables.records.IntervalsgameRecord;
import com.example.demo.jooq.tables.records.LevelintervalsRecord;
import com.example.demo.jooq.tables.records.LevelnotesRecord;
import com.example.demo.jooq.tables.records.NotesRecord;
import com.example.demo.jooq.tables.records.NotesgamesRecord;
import com.example.demo.jooq.tables.records.UsersRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AnswersintervalsgameRecord> KEY_ANSWERSINTERVALSGAME_PRIMARY = Internal.createUniqueKey(Answersintervalsgame.ANSWERSINTERVALSGAME, DSL.name("KEY_AnswersIntervalsGame_PRIMARY"), new TableField[] { Answersintervalsgame.ANSWERSINTERVALSGAME.ANSWERINTERVALSGAMEID }, true);
    public static final UniqueKey<AnswersnotesgameRecord> KEY_ANSWERSNOTESGAME_PRIMARY = Internal.createUniqueKey(Answersnotesgame.ANSWERSNOTESGAME, DSL.name("KEY_AnswersNotesGame_PRIMARY"), new TableField[] { Answersnotesgame.ANSWERSNOTESGAME.ANSWERSNOTESGAMEID }, true);
    public static final UniqueKey<IntervalsRecord> KEY_INTERVALS_PRIMARY = Internal.createUniqueKey(Intervals.INTERVALS, DSL.name("KEY_Intervals_PRIMARY"), new TableField[] { Intervals.INTERVALS.INTERVALID }, true);
    public static final UniqueKey<IntervalsgameRecord> KEY_INTERVALSGAME_PRIMARY = Internal.createUniqueKey(Intervalsgame.INTERVALSGAME, DSL.name("KEY_IntervalsGame_PRIMARY"), new TableField[] { Intervalsgame.INTERVALSGAME.INTERVALSGAMEID }, true);
    public static final UniqueKey<LevelintervalsRecord> KEY_LEVELINTERVALS_NAME = Internal.createUniqueKey(Levelintervals.LEVELINTERVALS, DSL.name("KEY_LevelIntervals_name"), new TableField[] { Levelintervals.LEVELINTERVALS.NAME }, true);
    public static final UniqueKey<LevelintervalsRecord> KEY_LEVELINTERVALS_PRIMARY = Internal.createUniqueKey(Levelintervals.LEVELINTERVALS, DSL.name("KEY_LevelIntervals_PRIMARY"), new TableField[] { Levelintervals.LEVELINTERVALS.LEVELID }, true);
    public static final UniqueKey<LevelnotesRecord> KEY_LEVELNOTES_NAME = Internal.createUniqueKey(Levelnotes.LEVELNOTES, DSL.name("KEY_LevelNotes_name"), new TableField[] { Levelnotes.LEVELNOTES.NAME }, true);
    public static final UniqueKey<LevelnotesRecord> KEY_LEVELNOTES_PRIMARY = Internal.createUniqueKey(Levelnotes.LEVELNOTES, DSL.name("KEY_LevelNotes_PRIMARY"), new TableField[] { Levelnotes.LEVELNOTES.LEVELID }, true);
    public static final UniqueKey<NotesRecord> KEY_NOTES_PRIMARY = Internal.createUniqueKey(Notes.NOTES, DSL.name("KEY_Notes_PRIMARY"), new TableField[] { Notes.NOTES.NOTEID }, true);
    public static final UniqueKey<NotesgamesRecord> KEY_NOTESGAMES_PRIMARY = Internal.createUniqueKey(Notesgames.NOTESGAMES, DSL.name("KEY_NotesGames_PRIMARY"), new TableField[] { Notesgames.NOTESGAMES.NOTESGAMEID }, true);
    public static final UniqueKey<UsersRecord> KEY_USERS_NAME = Internal.createUniqueKey(Users.USERS, DSL.name("KEY_Users_name"), new TableField[] { Users.USERS.NAME }, true);
    public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = Internal.createUniqueKey(Users.USERS, DSL.name("KEY_Users_PRIMARY"), new TableField[] { Users.USERS.USERID }, true);
}
