/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooq;


import com.example.demo.jooq.tables.Answersintervalsgame;
import com.example.demo.jooq.tables.Answersnotesgame;
import com.example.demo.jooq.tables.Intervals;
import com.example.demo.jooq.tables.Intervalsgame;
import com.example.demo.jooq.tables.Levelintervals;
import com.example.demo.jooq.tables.Levelnotes;
import com.example.demo.jooq.tables.Notes;
import com.example.demo.jooq.tables.Notesgames;
import com.example.demo.jooq.tables.Users;


/**
 * Convenience access to all tables in db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>db.AnswersIntervalsGame</code>.
     */
    public static final Answersintervalsgame ANSWERSINTERVALSGAME = Answersintervalsgame.ANSWERSINTERVALSGAME;

    /**
     * The table <code>db.AnswersNotesGame</code>.
     */
    public static final Answersnotesgame ANSWERSNOTESGAME = Answersnotesgame.ANSWERSNOTESGAME;

    /**
     * The table <code>db.Intervals</code>.
     */
    public static final Intervals INTERVALS = Intervals.INTERVALS;

    /**
     * The table <code>db.IntervalsGame</code>.
     */
    public static final Intervalsgame INTERVALSGAME = Intervalsgame.INTERVALSGAME;

    /**
     * The table <code>db.LevelIntervals</code>.
     */
    public static final Levelintervals LEVELINTERVALS = Levelintervals.LEVELINTERVALS;

    /**
     * The table <code>db.LevelNotes</code>.
     */
    public static final Levelnotes LEVELNOTES = Levelnotes.LEVELNOTES;

    /**
     * The table <code>db.Notes</code>.
     */
    public static final Notes NOTES = Notes.NOTES;

    /**
     * The table <code>db.NotesGames</code>.
     */
    public static final Notesgames NOTESGAMES = Notesgames.NOTESGAMES;

    /**
     * The table <code>db.Users</code>.
     */
    public static final Users USERS = Users.USERS;
}
