/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooq.tables.records;


import com.example.demo.jooq.tables.Answersintervalsgame;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnswersintervalsgameRecord extends UpdatableRecordImpl<AnswersintervalsgameRecord> implements Record5<Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>db.AnswersIntervalsGame.answerIntervalsGameID</code>.
     */
    public void setAnswerintervalsgameid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db.AnswersIntervalsGame.answerIntervalsGameID</code>.
     */
    public Integer getAnswerintervalsgameid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db.AnswersIntervalsGame.intervalsGameID</code>.
     */
    public void setIntervalsgameid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>db.AnswersIntervalsGame.intervalsGameID</code>.
     */
    public Integer getIntervalsgameid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>db.AnswersIntervalsGame.intervalID</code>.
     */
    public void setIntervalid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>db.AnswersIntervalsGame.intervalID</code>.
     */
    public Integer getIntervalid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>db.AnswersIntervalsGame.intervalOccurrences</code>.
     */
    public void setIntervaloccurrences(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>db.AnswersIntervalsGame.intervalOccurrences</code>.
     */
    public Integer getIntervaloccurrences() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>db.AnswersIntervalsGame.intervalGuessedCorrectly</code>.
     */
    public void setIntervalguessedcorrectly(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>db.AnswersIntervalsGame.intervalGuessedCorrectly</code>.
     */
    public Integer getIntervalguessedcorrectly() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Answersintervalsgame.ANSWERSINTERVALSGAME.ANSWERINTERVALSGAMEID;
    }

    @Override
    public Field<Integer> field2() {
        return Answersintervalsgame.ANSWERSINTERVALSGAME.INTERVALSGAMEID;
    }

    @Override
    public Field<Integer> field3() {
        return Answersintervalsgame.ANSWERSINTERVALSGAME.INTERVALID;
    }

    @Override
    public Field<Integer> field4() {
        return Answersintervalsgame.ANSWERSINTERVALSGAME.INTERVALOCCURRENCES;
    }

    @Override
    public Field<Integer> field5() {
        return Answersintervalsgame.ANSWERSINTERVALSGAME.INTERVALGUESSEDCORRECTLY;
    }

    @Override
    public Integer component1() {
        return getAnswerintervalsgameid();
    }

    @Override
    public Integer component2() {
        return getIntervalsgameid();
    }

    @Override
    public Integer component3() {
        return getIntervalid();
    }

    @Override
    public Integer component4() {
        return getIntervaloccurrences();
    }

    @Override
    public Integer component5() {
        return getIntervalguessedcorrectly();
    }

    @Override
    public Integer value1() {
        return getAnswerintervalsgameid();
    }

    @Override
    public Integer value2() {
        return getIntervalsgameid();
    }

    @Override
    public Integer value3() {
        return getIntervalid();
    }

    @Override
    public Integer value4() {
        return getIntervaloccurrences();
    }

    @Override
    public Integer value5() {
        return getIntervalguessedcorrectly();
    }

    @Override
    public AnswersintervalsgameRecord value1(Integer value) {
        setAnswerintervalsgameid(value);
        return this;
    }

    @Override
    public AnswersintervalsgameRecord value2(Integer value) {
        setIntervalsgameid(value);
        return this;
    }

    @Override
    public AnswersintervalsgameRecord value3(Integer value) {
        setIntervalid(value);
        return this;
    }

    @Override
    public AnswersintervalsgameRecord value4(Integer value) {
        setIntervaloccurrences(value);
        return this;
    }

    @Override
    public AnswersintervalsgameRecord value5(Integer value) {
        setIntervalguessedcorrectly(value);
        return this;
    }

    @Override
    public AnswersintervalsgameRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AnswersintervalsgameRecord
     */
    public AnswersintervalsgameRecord() {
        super(Answersintervalsgame.ANSWERSINTERVALSGAME);
    }

    /**
     * Create a detached, initialised AnswersintervalsgameRecord
     */
    public AnswersintervalsgameRecord(Integer answerintervalsgameid, Integer intervalsgameid, Integer intervalid, Integer intervaloccurrences, Integer intervalguessedcorrectly) {
        super(Answersintervalsgame.ANSWERSINTERVALSGAME);

        setAnswerintervalsgameid(answerintervalsgameid);
        setIntervalsgameid(intervalsgameid);
        setIntervalid(intervalid);
        setIntervaloccurrences(intervaloccurrences);
        setIntervalguessedcorrectly(intervalguessedcorrectly);
    }
}
