/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooq.tables.records;


import com.example.demo.jooq.tables.Intervalsgame;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IntervalsgameRecord extends UpdatableRecordImpl<IntervalsgameRecord> implements Record4<Integer, Integer, Integer, LocalDate> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>db.IntervalsGame.intervalsGameID</code>.
     */
    public void setIntervalsgameid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db.IntervalsGame.intervalsGameID</code>.
     */
    public Integer getIntervalsgameid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db.IntervalsGame.intervalLevelID</code>.
     */
    public void setIntervallevelid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>db.IntervalsGame.intervalLevelID</code>.
     */
    public Integer getIntervallevelid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>db.IntervalsGame.userID</code>.
     */
    public void setUserid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>db.IntervalsGame.userID</code>.
     */
    public Integer getUserid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>db.IntervalsGame.datePlayed</code>.
     */
    public void setDateplayed(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>db.IntervalsGame.datePlayed</code>.
     */
    public LocalDate getDateplayed() {
        return (LocalDate) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, LocalDate> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, Integer, LocalDate> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Intervalsgame.INTERVALSGAME.INTERVALSGAMEID;
    }

    @Override
    public Field<Integer> field2() {
        return Intervalsgame.INTERVALSGAME.INTERVALLEVELID;
    }

    @Override
    public Field<Integer> field3() {
        return Intervalsgame.INTERVALSGAME.USERID;
    }

    @Override
    public Field<LocalDate> field4() {
        return Intervalsgame.INTERVALSGAME.DATEPLAYED;
    }

    @Override
    public Integer component1() {
        return getIntervalsgameid();
    }

    @Override
    public Integer component2() {
        return getIntervallevelid();
    }

    @Override
    public Integer component3() {
        return getUserid();
    }

    @Override
    public LocalDate component4() {
        return getDateplayed();
    }

    @Override
    public Integer value1() {
        return getIntervalsgameid();
    }

    @Override
    public Integer value2() {
        return getIntervallevelid();
    }

    @Override
    public Integer value3() {
        return getUserid();
    }

    @Override
    public LocalDate value4() {
        return getDateplayed();
    }

    @Override
    public IntervalsgameRecord value1(Integer value) {
        setIntervalsgameid(value);
        return this;
    }

    @Override
    public IntervalsgameRecord value2(Integer value) {
        setIntervallevelid(value);
        return this;
    }

    @Override
    public IntervalsgameRecord value3(Integer value) {
        setUserid(value);
        return this;
    }

    @Override
    public IntervalsgameRecord value4(LocalDate value) {
        setDateplayed(value);
        return this;
    }

    @Override
    public IntervalsgameRecord values(Integer value1, Integer value2, Integer value3, LocalDate value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IntervalsgameRecord
     */
    public IntervalsgameRecord() {
        super(Intervalsgame.INTERVALSGAME);
    }

    /**
     * Create a detached, initialised IntervalsgameRecord
     */
    public IntervalsgameRecord(Integer intervalsgameid, Integer intervallevelid, Integer userid, LocalDate dateplayed) {
        super(Intervalsgame.INTERVALSGAME);

        setIntervalsgameid(intervalsgameid);
        setIntervallevelid(intervallevelid);
        setUserid(userid);
        setDateplayed(dateplayed);
    }
}
