/*
 * This file is generated by jOOQ.
 */
package com.example.demo.jooq.tables.records;


import com.example.demo.jooq.tables.Notesgames;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotesgamesRecord extends UpdatableRecordImpl<NotesgamesRecord> implements Record4<Integer, Integer, Integer, LocalDate> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>db.NotesGames.notesGameID</code>.
     */
    public void setNotesgameid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db.NotesGames.notesGameID</code>.
     */
    public Integer getNotesgameid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db.NotesGames.userID</code>.
     */
    public void setUserid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>db.NotesGames.userID</code>.
     */
    public Integer getUserid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>db.NotesGames.levelNotesID</code>.
     */
    public void setLevelnotesid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>db.NotesGames.levelNotesID</code>.
     */
    public Integer getLevelnotesid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>db.NotesGames.datePlayed</code>.
     */
    public void setDateplayed(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>db.NotesGames.datePlayed</code>.
     */
    public LocalDate getDateplayed() {
        return (LocalDate) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, LocalDate> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, Integer, LocalDate> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Notesgames.NOTESGAMES.NOTESGAMEID;
    }

    @Override
    public Field<Integer> field2() {
        return Notesgames.NOTESGAMES.USERID;
    }

    @Override
    public Field<Integer> field3() {
        return Notesgames.NOTESGAMES.LEVELNOTESID;
    }

    @Override
    public Field<LocalDate> field4() {
        return Notesgames.NOTESGAMES.DATEPLAYED;
    }

    @Override
    public Integer component1() {
        return getNotesgameid();
    }

    @Override
    public Integer component2() {
        return getUserid();
    }

    @Override
    public Integer component3() {
        return getLevelnotesid();
    }

    @Override
    public LocalDate component4() {
        return getDateplayed();
    }

    @Override
    public Integer value1() {
        return getNotesgameid();
    }

    @Override
    public Integer value2() {
        return getUserid();
    }

    @Override
    public Integer value3() {
        return getLevelnotesid();
    }

    @Override
    public LocalDate value4() {
        return getDateplayed();
    }

    @Override
    public NotesgamesRecord value1(Integer value) {
        setNotesgameid(value);
        return this;
    }

    @Override
    public NotesgamesRecord value2(Integer value) {
        setUserid(value);
        return this;
    }

    @Override
    public NotesgamesRecord value3(Integer value) {
        setLevelnotesid(value);
        return this;
    }

    @Override
    public NotesgamesRecord value4(LocalDate value) {
        setDateplayed(value);
        return this;
    }

    @Override
    public NotesgamesRecord values(Integer value1, Integer value2, Integer value3, LocalDate value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotesgamesRecord
     */
    public NotesgamesRecord() {
        super(Notesgames.NOTESGAMES);
    }

    /**
     * Create a detached, initialised NotesgamesRecord
     */
    public NotesgamesRecord(Integer notesgameid, Integer userid, Integer levelnotesid, LocalDate dateplayed) {
        super(Notesgames.NOTESGAMES);

        setNotesgameid(notesgameid);
        setUserid(userid);
        setLevelnotesid(levelnotesid);
        setDateplayed(dateplayed);
    }
}
